import type { Client, CompanyProfile, Expense, Invoice, Payment, Project } from "@/types/finance";

export const companyProfile: CompanyProfile = {
  name: "Motion Mirage Studios",
  tagline: "A Production Agency",
  address: "188/1 Block - J, New Alipore, Kolkata - 700053",
  phone: "+91 8334046481",
  email: "atanuroyofficial@gmail.com",
  website: "motionmirage.studio",
  gstNumber: "19ABCDE1234F1Z5",
  panNumber: "ABCDE1234F",
  bankDetails: "HDFC Bank • A/C 50200012345678 • IFSC HDFC0001234",
  upiDetails: "motionmirage@upi",
  paymentTerms: "Payment due within 15 days from invoice date.",
  invoiceNotes:
    "Thank you for choosing Motion Mirage Studios. Please make payment via bank transfer or UPI before the due date.",
  quotationTerms: "This quotation is valid for 15 days from the date of issue.",
};

export const clients: Client[] = [
  {
    id: "cli-001",
    name: "ABC Films",
    contactPerson: "Ritika Sen",
    email: "ritika@abcfilms.in",
    phone: "+91 9876543210",
    billingAddress: "18 Studio Road, Kolkata",
    currency: "INR",
    gst: "19AAACF1111A1Z9",
    paymentTerms: "Net 15",
    notes: "Preferred monthly billing.",
    outstandingBalance: 24000,
  },
  {
    id: "cli-002",
    name: "Horizon Lights",
    contactPerson: "Arjun Das",
    email: "arjun@horizonlights.io",
    phone: "+91 9123456780",
    billingAddress: "Banjara Hills, Hyderabad",
    currency: "INR",
    gst: "36AAZEH9876C1Z2",
    paymentTerms: "Net 30",
    notes: "Short turnaround project.",
    outstandingBalance: 35000,
  },
  {
    id: "cli-003",
    name: "North Star Media",
    contactPerson: "Naina Roy",
    email: "naina@northstar.media",
    phone: "+91 9933221122",
    billingAddress: "Salt Lake, Kolkata",
    currency: "INR",
    gst: "19AABCN8899C1Z0",
    paymentTerms: "Net 30",
    notes: "Long-term retainer client.",
    outstandingBalance: 0,
  },
];

export const projects: Project[] = [
  {
    id: "prj-101",
    name: "Brand Film Production",
    clientId: "cli-001",
    description: "Two-day shoot and edit for a contemporary brand campaign.",
    startDate: "2026-08-01",
    shootDate: "2026-08-15",
    deliveryDate: "2026-08-29",
    quotationAmount: 50000,
    invoiceAmount: 50000,
    paymentsReceived: 26000,
    projectExpenses: 18000,
    status: "Completed",
    billingStatus: "Partially Paid",
    notes: "Campaign delivered with revisions.",
  },
  {
    id: "prj-102",
    name: "Corporate Event Coverage",
    clientId: "cli-002",
    description: "Live event production with highlight edits and post-production.",
    startDate: "2026-09-01",
    shootDate: "2026-09-20",
    deliveryDate: "2026-10-02",
    quotationAmount: 92000,
    invoiceAmount: 92000,
    paymentsReceived: 57000,
    projectExpenses: 33000,
    status: "In Production",
    billingStatus: "Partially Paid",
    notes: "Final edit pending.",
  },
  {
    id: "prj-103",
    name: "Product Launch Reel",
    clientId: "cli-003",
    description: "Short-form launch reel in 4K with motion graphics.",
    startDate: "2026-07-15",
    shootDate: "2026-07-28",
    deliveryDate: "2026-08-12",
    quotationAmount: 67000,
    invoiceAmount: 67000,
    paymentsReceived: 67000,
    projectExpenses: 44000,
    status: "Delivered",
    billingStatus: "Paid",
    notes: "Client approved and final payment received.",
  },
];

export const invoices: Invoice[] = [
  {
    id: "inv-001",
    number: "MMS-INV-2026-001",
    clientId: "cli-001",
    projectId: "prj-101",
    invoiceDate: "2026-08-12",
    dueDate: "2026-08-27",
    status: "Partially Paid",
    subtotal: 50000,
    discount: 0,
    tax: 0,
    total: 50000,
    paid: 26000,
    outstanding: 24000,
    items: [
      { description: "2-day shoot and editing package", quantity: 1, rate: 50000, discount: 0, tax: 0 },
    ],
    notes: "Includes editing, color grading, and delivery master files.",
  },
  {
    id: "inv-002",
    number: "MMS-INV-2026-002",
    clientId: "cli-002",
    projectId: "prj-102",
    invoiceDate: "2026-09-05",
    dueDate: "2026-09-20",
    status: "Sent",
    subtotal: 92000,
    discount: 0,
    tax: 0,
    total: 92000,
    paid: 57000,
    outstanding: 35000,
    items: [
      { description: "Corporate event coverage package", quantity: 1, rate: 92000, discount: 0, tax: 0 },
    ],
    notes: "Balance due upon final delivery confirmation.",
  },
  {
    id: "inv-003",
    number: "MMS-INV-2026-003",
    clientId: "cli-003",
    projectId: "prj-103",
    invoiceDate: "2026-07-25",
    dueDate: "2026-08-09",
    status: "Paid",
    subtotal: 67000,
    discount: 0,
    tax: 0,
    total: 67000,
    paid: 67000,
    outstanding: 0,
    items: [
      { description: "Product launch reel with 4K export", quantity: 1, rate: 67000, discount: 0, tax: 0 },
    ],
    notes: "Project completed and finalized.",
  },
];

export const payments: Payment[] = [
  {
    id: "pay-001",
    invoiceId: "inv-001",
    clientId: "cli-001",
    projectId: "prj-101",
    amount: 26000,
    date: "2026-08-20",
    method: "Bank Transfer",
    reference: "UPI-20260820-1653",
    notes: "Partial payment against the first invoice.",
  },
  {
    id: "pay-002",
    invoiceId: "inv-002",
    clientId: "cli-002",
    projectId: "prj-102",
    amount: 57000,
    date: "2026-09-08",
    method: "Bank Transfer",
    reference: "NEFT-89011",
    notes: "Advance payment for production work.",
  },
  {
    id: "pay-003",
    invoiceId: "inv-003",
    clientId: "cli-003",
    projectId: "prj-103",
    amount: 67000,
    date: "2026-08-05",
    method: "UPI",
    reference: "UPI-67000-1",
    notes: "Final settlement.",
  },
];

export const expenses: Expense[] = [
  {
    id: "exp-001",
    date: "2026-08-12",
    category: "Equipment rental",
    vendor: "FrameWorks Rentals",
    amount: 9000,
    projectId: "prj-101",
    method: "Bank Transfer",
    reference: "RF-1088",
    notes: "Camera and lighting rental for the shoot.",
  },
  {
    id: "exp-002",
    date: "2026-09-03",
    category: "Travel",
    vendor: "BlueJet Logistics",
    amount: 6400,
    projectId: "prj-102",
    method: "Cash",
    reference: "TRV-204",
    notes: "Team travel and local transit.",
  },
  {
    id: "exp-003",
    date: "2026-09-10",
    category: "Software",
    vendor: "Adobe Creative Cloud",
    amount: 3500,
    projectId: undefined,
    method: "Card",
    reference: "AD-776",
    notes: "Monthly editing software subscription.",
  },
];

export const incomeSummary = {
  totalInvoiced: invoices.reduce((sum, invoice) => sum + invoice.total, 0),
  totalReceived: payments.reduce((sum, payment) => sum + payment.amount, 0),
  totalOutstanding: invoices.reduce((sum, invoice) => sum + invoice.outstanding, 0),
  totalExpenses: expenses.reduce((sum, expense) => sum + expense.amount, 0),
  netCashResult: payments.reduce((sum, payment) => sum + payment.amount, 0) - expenses.reduce((sum, expense) => sum + expense.amount, 0),
};

export const formatCurrency = (value: number) =>
  new Intl.NumberFormat("en-IN", {
    style: "currency",
    currency: "INR",
    maximumFractionDigits: 0,
  }).format(value);
