import Link from "next/link";
import { notFound } from "next/navigation";
import { db } from "@/lib/db";
import { formatCurrency } from "@/lib/mock-data";
import { requireAuth } from "@/lib/require-auth";
import { InvoiceActions } from "@/components/invoice-actions";

export default async function InvoiceDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const session = await requireAuth();
  const { id } = await params;
  const invoice = await db.invoice.findFirst({ where: { id, ownerId: session.user.id }, include: { client: true, items: true } });
  if (!invoice) notFound();
  return <main className="p-8"><Link className="text-button no-print" href="/invoices">← Back to invoices</Link><div className="invoice-detail-heading no-print"><div><p className="eyebrow">Invoice record</p><h1 className="text-3xl font-bold">{invoice.number}</h1><p className="muted">{invoice.client.name} · {invoice.invoiceDate.toISOString().slice(0, 10)}</p></div><InvoiceActions invoiceId={invoice.id} /></div><article className="invoice-paper saved-invoice-paper"><header className="invoice-header"><div><h2>INVOICE</h2><div className="company-details"><strong>Motion Mirage Studios</strong><span>A Production Agency</span><span>Company address</span><span>Phone and email on file</span></div></div><div className="brand-mark"><span>MOTION</span><b>MIRAGE</b><small>STUDIOS</small></div></header><div className="invoice-meta"><div><span>Invoice number</span><strong>{invoice.number}</strong></div><div><span>Issue date</span><strong>{invoice.invoiceDate.toISOString().slice(0, 10)}</strong></div><div><span>Due date</span><strong>{invoice.dueDate.toISOString().slice(0, 10)}</strong></div></div><div className="bill-to"><div className="block-label">Billed to</div><strong>{invoice.client.name}</strong><span>{invoice.client.billingAddress}</span><span>{invoice.client.email}</span><span>{invoice.client.phone}</span></div><div className="service-heading"><h3>Description of services</h3><span>{invoice.items.length} line{invoice.items.length === 1 ? "" : "s"}</span></div><table className="service-table"><thead><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>{invoice.items.map((item) => <tr key={item.id}><td>{item.description}</td><td>{item.quantity}</td><td>{formatCurrency(item.rate)}</td><td>{formatCurrency(item.quantity * item.rate)}</td></tr>)}</tbody></table><div className="invoice-total"><span>Total due</span><strong>{formatCurrency(invoice.total)}</strong></div><div className="invoice-footer"><div><div className="block-label">Payment note</div><p>{invoice.notes || "Payment due according to the agreed terms."}</p></div><div className="thank-you">Thank you<br /><strong>for your business.</strong></div></div></article></main>;
}